language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements-dev.txt
  - pip install .
# command to run tests
script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - pytest